### PR TITLE
增加多语言支持

### PR DESCRIPTION
**Pull request by zaoqi**
未完成

### CODE REVIEW

**Comment by zaoqi** [comment]
What's "Aston Maaton","Nizzan","Lambogoni","Masda","Musting",”Fewawi","Geep","Pooshe" and "Wheel"?

**Comment by zaoqi** [comment]
Can you use "The GNU Affero General Public License"?

**Comment by zaoqi** [comment]
这个语言文件是用我的一个*.sh自动翻译的，所以暂时不要合并。

**Comment by zaoqi** [comment]
现在完成了

**Comment by D00Med** [comment]
Wheel is the only real word in that list, it's explained easiest with an image: http://www.tirerack.com/content/dam/tirerack/desktop/wheel/TireWheelStack.jpg
The other names are all misspelt car company names, like Porsche, Aston martin etc.
Why would I want to change the license?

**Comment by D00Med** [comment]
Also why does the code now check for the vehicle's health when the driver punches it?

**Comment by zaoqi** [comment]
如果这个mod被用在服务器上，不需要公开源代码。
Baidu Translate（Chinese can't use Google）:
Dont't need to expose the source code if this mod is used on the server.

**Comment by zaoqi** [comment]
用拳打载具，重新放置它可以修复它。

**Comment by D00Med** [comment]
I will keep the license as it is.
Thanks for your help with this mod

**Pull request merged**
