### PR TITLE
Bunch of fixes

### PR DESCRIPTION
**Pull request by rollerozxa**
Bunch of fixes, including turning `default`, `tnt` and `dye` into optional dependencies making it more game-agnostic (works in build game now, along with others), and fixing a lot of deprecation warnings.

### CODE REVIEW

**Comment by D00Med** [comment]
Removing the "unused source" is a bad thing if anyone ever wants to clean up / fix this mod.

Good work though

**Comment by rollerozxa** [comment]
Oh, is the newer API somehow slower? I guess I could give optimising it a go.

**Comment by rollerozxa** [comment]
Ok so I did some tiny optimisations. Every vehicle step is now sitting on an even more stable <2ms rate (it was pretty fine previously) and it keeps up well when playing with a significantly lowered `dedicated_server_step` (all this on my Phenom, mind you), so I don't know what other performance issues there is. If it turns out to really be an issue then the Git history always exists.

**Comment by D00Med** [comment]
> Oh, is the newer API somehow slower? I guess I could give optimising it a go.
It doesn't work well to use the same function for boats, planes, and ground vehicles. To improve any one, it becomes very difficult compared to when they were split. I suppose the old API should still just go. 

Thankyou for working on this ^^

**Comment by rollerozxa** [comment]
and thank you for merging! :smile: I also went ahead and made a new release on ContentDB with the new changes included.

**Pull request merged**
