### PR TITLE
Add compatibility with Moreblocks

### PR DESCRIPTION
**Pull request by Jat15**
2328-2366
Add all block with function simplenode in moreblocks or stairs if not light

And Code formatting

### CODE REVIEW

**Comment by D00Med** [comment]
Thanks for this :)

**Comment by Jat15** [comment]
Would not you like one change?

**Comment by D00Med** [comment]
I haven't merged this yet because I was working on an update.

**Comment by Jat15** [comment]
Thx for reply.

**Comment by D00Med** [comment]
@Jat15 You're welcome

**Comment by D00Med** [comment]
I'm sorry I never got around to merging this

**Pull request closed without merging**
